---

- name: Install Nginx on Debian
  apt: name=nginx state=latest update_cache=yes
  
- name: Start And Enable Nginx
  service: name=nginx enabled=yes state=started

- name: Edit and Backup Nginx Config
  copy: 
     src: roles/nginx/files/nginx.conf
     dest: /etc/nginx/nginx.conf
     mode: '0644'
     backup: yes
  notify: Restart Nginx
