---

- name: Install Cool Shell Housekeeping (vim, z-shell, tmux)
  apt: name={{ item }} update_cache=yes state=latest
  with_items:
     - vim
     - tmux
     - zsh

- name: Change Shell to Z-Shell
  user: 
     name: {{ ansible_user_id }}
     shell: /bin/zsh
